---
job: &job
  public: false
  serial: true

get_source: &get_source
  get: source
  trigger: true

get_source_publish: &get_source_publish
  <<: *get_source
  trigger: false
  passed:
  - test-build

get_version: &get_version
  get: version
  trigger: false

put_version: &put_version
  put: version
  attempts: 3
  params:
    file: version/version

task_publish_nugget: &task_publish_nugget
  in_parallel:
  - task: pdfsharpcore
    file: source/.ci/tasks/publish-nugget.yaml
    attempts: 3
    params:
      PROJECT: PdfSharpCore
      NUGGET_TAGS: "PdfSharp .NETCore"

  - task: migradoccore.documentobjectmodel
    file: source/.ci/tasks/publish-nugget.yaml
    attempts: 3
    params:
      PROJECT: MigraDocCore.DocumentObjectModel
      NUGGET_TAGS: "MigraDoc ObjectModel .NETCore"

  - task: migradoccore.rendering
    file: source/.ci/tasks/publish-nugget.yaml
    attempts: 3
    params:
      PROJECT: MigraDocCore.Rendering
      NUGGET_TAGS: "MigraDoc Rendering .NETCore"

  - task: pdfsharpcore.charting
    file: source/.ci/tasks/publish-nugget.yaml
    attempts: 3
    params:
      PROJECT: PdfSharpCore.Charting
      NUGGET_TAGS: "PdfSharp Charting .NETCore"

#-----------------------------------------------------------------------------------------------------------------------
# Resources
#-----------------------------------------------------------------------------------------------------------------------
resources:
- name: source
  type: git
  source:
    uri: https://github.com/ststeiger/PdfSharpCore.git
    branch: master

- name: version
  type: semver
  source:
    driver: s3
    bucket: startnow65
    key: concourse/pdfsharpcore-semver
    region_name: us-west-2
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))

#-----------------------------------------------------------------------------------------------------------------------
# Jobs
#-----------------------------------------------------------------------------------------------------------------------
jobs:

# Would be replace with proper Unit/Integration tests
- name: test-build
  <<: *job
  plan:
  - <<: *get_source
  - in_parallel:
    - task: pdfsharpcore
      file: source/.ci/tasks/build.yaml
      attempts: 3
      params:
        PROJECT: PdfSharpCore

    - task: migradoccore.documentobjectmodel
      file: source/.ci/tasks/build.yaml
      attempts: 3
      params:
        PROJECT: MigraDocCore.DocumentObjectModel

    - task: migradoccore.rendering
      file: source/.ci/tasks/build.yaml
      attempts: 3
      params:
        PROJECT: MigraDocCore.Rendering

    - task: pdfsharpcore.charting
      file: source/.ci/tasks/build.yaml
      attempts: 3
      params:
        PROJECT: PdfSharpCore.Charting

- name: publish-patch
  <<: *job
  plan:
  - in_parallel:
    - <<: *get_source_publish
      trigger: true
    - <<: *get_version
      params:
        bump: patch

  - <<: *put_version
  - <<: *task_publish_nugget

- name: publish-minor
  <<: *job
  plan:
  - in_parallel:
    - <<: *get_source_publish
    - <<: *get_version
      params:
        bump: minor

  - <<: *put_version
  - <<: *task_publish_nugget

- name: publish-major
  <<: *job
  plan:
  - in_parallel:
    - <<: *get_source_publish
    - <<: *get_version
      params:
        bump: major

  - <<: *put_version
  - <<: *task_publish_nugget
